export enum EMAILTEMPLATE {
  WELCOME = 'WELCOME',
  VERIFY_MAIL = 'VERIFY_MAIL',
  RESET_PASSWORD = 'RESET_PASSWORD',
  ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',
  ORDER_CANCELLATION = 'ORDER_CANCELLATION',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
}
