stages:
  - deploy

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk update && apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /var/www/idea-investment-webapp && source deploy-api.sh && exit"
  only:
    - main
